# -*- coding: utf-8 -*-
"""Travel_Review.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jE5sk-Oe5z508gu2DhI7Do_ZjS86W7vi

#Análise de dados travel review
"""

import pandas as pd

MicrodadosTravelReview = pd.read_csv ("C:\travel review\tripadvisor_review.csv")

MicrodadosTravelReview = pd.read_csv ("C:\travel review\tripadvisor_review.csv", sep="," ,  encoding= "UTF-8")

MicrodadosTravelReview = pd.read_csv ('C:\travel review\tripadvisor_review.csv', sep=',' ,  encoding= 'UTF-8')

MicrodadosTravelReview = pd.read_csv ("C:\travel review\tripadvisor_review.csv", sep="," ,  encoding= "UTF-8")

MicrodadosTravelReview = pd.read_csv (r"C:\travel review\tripadvisor_review.csv", sep="," ,  encoding= "UTF-8")

MicrodadosTravelReview.head()

MicrodadosTravelReview

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,                    
                                                    test_size=0.3,
                                                    random_state=42)

MicrodadosTravelReview = pd.read_csv (r"C:\temp\travel_review_bd.csv", sep="," ,  encoding= "UTF-8")

MicrodadosTravelReview

MicrodadosTravelReview = pd.read_csv (r"C:\temp\travel_review_bd.csv", sep=";" ,  encoding= "UTF-8")

MicrodadosTravelReview

features = ['Cat_Galleries', 'Cat_Dance', 'Cat_Juice_Bars', 'Cat_Restaurants', 
            'Cat_Museums', 'Cat_Resorts', 'Cat_Parks', 'Cat_Beaches', 'Cat_Theaters', 
            'Cat_Religious']
x_train = df_train[features]

features = ['Cat_Galleries', 'Cat_Dance', 'Cat_Juice_Bars', 'Cat_Restaurants', 
            'Cat_Museums', 'Cat_Resorts', 'Cat_Parks', 'Cat_Beaches', 'Cat_Theaters', 
            'Cat_Religious']
x_train = MicrodadosTravelReview[features]

print(set(MicrodadosTravelReview.columns).issubset(set(MicrodadosTravelReview.columns)))

TravelReviewTrain = pd.read_csv (r"C:\temp\travel_review_train.csv", sep=";" ,  encoding= "UTF-8")

TravelReviewTest = pd.read_csv (r"C:\temp\travel_review_test.csv", sep=";" ,  encoding= "UTF-8")

print(set(TravelReviewTrain.columns).issubset(set(TravelReviewTest.columns)))

features = ['Cat_Galleries', 'Cat_Dance', 'Cat_Juice_Bars', 'Cat_Restaurants', 
            'Cat_Museums', 'Cat_Resorts', 'Cat_Parks', 'Cat_Beaches', 'Cat_Theaters', 
            'Cat_Religious']
x_train = TravelReviewTrain[features]

features = ['Cat_Galleries', 'Cat_Dance', 'Cat_Juice_Bars', 'Cat_Restaurants', 
            'Cat_Museums', 'Cat_Resorts', 'Cat_Parks', 'Cat_Beaches', 'Cat_Theaters', 
            'Cat_Religious']
x_train = TravelReviewTest[features]

TravelReviewTest[features].sum()/490

TravelReviewTest[features].sum()/490

TravelReviewTrain[features].sum()/490

